/**
 * Type-safe image manifest API
 * Provides utilities for querying optimized images generated by build-images.ts
 */

import rawManifest from '../image-manifest.json';

const manifest = rawManifest as ImageManifest;

export interface ImageVariant {
  width: number;
  format: 'webp' | 'avif';
  filename: string;
  size: number;
  url: string;
}

export interface ImageManifestEntry {
  id: string;
  original: string;
  originalWidth: number;
  originalHeight: number;
  originalSize: number;
  variants: ImageVariant[];
  srcset: string;
  avifSrcset: string;
  sizes: string;
  blurDataURL: string;
  aspectRatio: number;
}

export interface ImageManifest {
  version: string;
  generated: string;
  images: Record<string, ImageManifestEntry>;
}

export interface OptimizedImageOptions {
  sizes?: string;
  priority?: boolean;
  loading?: 'lazy' | 'eager';
  decoding?: 'async' | 'sync';
  className?: string;
  style?: React.CSSProperties;
  alt: string;
}

function isValidManifest(data: unknown): data is ImageManifest {
  if (!data || typeof data !== 'object') return false;
  const m = data as Record<string, unknown>;
  return typeof m.version === 'string' && typeof m.generated === 'string' && typeof m.images === 'object';
}

function transformManifest(data: unknown): ImageManifest {
  if (!isValidManifest(data)) {
    return { version: '1.0.0', generated: new Date().toISOString(), images: {} };
  }
  
  const images: Record<string, ImageManifestEntry> = {};
  
  for (const [key, entry] of Object.entries(data.images)) {
    images[key] = {
      id: entry.id,
      original: entry.original,
      originalWidth: entry.originalWidth,
      originalHeight: entry.originalHeight,
      originalSize: entry.originalSize,
      variants: entry.variants.map(v => ({
        width: v.width,
        format: v.format as 'webp' | 'avif',
        filename: v.filename,
        size: v.size,
        url: v.url,
      })),
      srcset: entry.srcset,
      avifSrcset: entry.avifSrcset,
      sizes: entry.sizes,
      blurDataURL: entry.blurDataURL,
      aspectRatio: entry.aspectRatio,
    };
  }
  
  return {
    version: data.version,
    generated: data.generated,
    images,
  };
}

const imageManifest = transformManifest(manifest);

/**
 * Find an image by its original path
 * @param originalPath - The original image path (e.g., "/images/photo.jpg")
 * @returns The image manifest entry or null if not found
 */
export function getImageByPath(originalPath: string): ImageManifestEntry | null {
  const normalizedPath = originalPath.startsWith('/') ? originalPath : `/${originalPath}`;
  
  for (const entry of Object.values(imageManifest.images)) {
    if (entry.original === normalizedPath) {
      return entry;
    }
  }
  
  return null;
}

/**
 * Find an image by its ID (hash)
 * @param id - The image ID (hash)
 * @returns The image manifest entry or null if not found
 */
export function getImageById(id: string): ImageManifestEntry | null {
  return imageManifest.images[id] || null;
}

/**
 * Get the best matching variant for a given width
 * @param entry - The image manifest entry
 * @param targetWidth - The target width in pixels
 * @param format - Preferred format ('webp' | 'avif')
 * @returns The best matching variant or null
 */
export function getVariantForWidth(
  entry: ImageManifestEntry,
  targetWidth: number,
  format: 'webp' | 'avif' = 'webp'
): ImageVariant | null {
  const variants = entry.variants
    .filter(v => v.format === format && v.width >= targetWidth)
    .sort((a, b) => a.width - b.width);
  
  if (variants.length === 0) {
    const allVariants = entry.variants.filter(v => v.format === format);
    if (allVariants.length > 0) {
      return allVariants[allVariants.length - 1];
    }
  }
  
  return variants[0] || null;
}

/**
 * Get all available variants for an image
 * @param entry - The image manifest entry
 * @param format - Filter by format
 * @returns Array of image variants
 */
export function getVariants(entry: ImageManifestEntry, format?: 'webp' | 'avif'): ImageVariant[] {
  if (format) {
    return entry.variants.filter(v => v.format === format);
  }
  return entry.variants;
}

/**
 * Generate srcset string for given widths
 * @param entry - The image manifest entry
 * @param widths - Array of widths to include
 * @param format - Format to use
 * @returns srcset string
 */
export function generateSrcSet(
  entry: ImageManifestEntry,
  widths: number[],
  format: 'webp' | 'avif' = 'webp'
): string {
  const variants = widths
    .map(w => getVariantForWidth(entry, w, format))
    .filter((v): v is ImageVariant => v !== null)
    .map(v => `${v.url} ${v.width}w`);
  
  return variants.join(', ');
}

/**
 * Get the smallest variant for lazy loading placeholder
 * @param entry - The image manifest entry
 * @param format - Format to use
 * @returns Smallest variant or null
 */
export function getSmallestVariant(entry: ImageManifestEntry, format: 'webp' | 'avif' = 'webp'): ImageVariant | null {
  const variants = entry.variants.filter(v => v.format === format);
  if (variants.length === 0) return null;
  return variants.reduce((min, v) => v.width < min.width ? v : min);
}

/**
 * Get all registered images
 * @returns Array of all image manifest entries
 */
export function getAllImages(): ImageManifestEntry[] {
  return Object.values(imageManifest.images);
}

/**
 * Get manifest metadata
 */
export function getManifestInfo(): { version: string; generated: string; imageCount: number } {
  return {
    version: imageManifest.version,
    generated: imageManifest.generated,
    imageCount: Object.keys(imageManifest.images).length,
  };
}

/**
 * Check if an image exists in the manifest
 * @param originalPath - The original image path
 * @returns True if image exists
 */
export function hasImage(originalPath: string): boolean {
  return getImageByPath(originalPath) !== null;
}