/**
 * Type-safe image manifest API
 * Provides utilities for querying optimized images generated by build-images.ts
 */

import rawManifest from "../image-manifest.json" with { type: "json" };

export interface ImageVariant {
  width: number;
  format: "webp" | "avif";
  filename: string;
  size: number;
  url: string;
}

export interface ImageManifestEntry {
  id: string;
  original: string;
  originalWidth: number;
  originalHeight: number;
  originalSize: number;
  variants: ImageVariant[];
  srcset: string;
  avifSrcset: string;
  sizes: string;
  blurDataURL: string;
  aspectRatio: number;
}

export interface ImageManifest {
  version: string;
  generated: string;
  images: Record<string, ImageManifestEntry>;
}

export interface OptimizedImageOptions {
  sizes?: string;
  priority?: boolean;
  loading?: "lazy" | "eager";
  decoding?: "async" | "sync";
  className?: string;
  style?: React.CSSProperties;
  alt: string;
}

/** Type guard for manifest validation */
function isValidManifest(data: unknown): data is ImageManifest {
  if (!data || typeof data !== "object") return false;

  const m = data as Record<string, unknown>;
  return (
    typeof m.version === "string" &&
    typeof m.generated === "string" &&
    typeof m.images === "object" &&
    m.images !== null
  );
}

/** Transform and validate raw JSON manifest */
function createManifest(data: unknown): ImageManifest {
  if (!isValidManifest(data)) {
    console.warn("⚠️ Invalid image manifest, using empty fallback");
    return {
      version: "1.0.0",
      generated: new Date().toISOString(),
      images: {},
    };
  }

  const images: Record<string, ImageManifestEntry> = {};

  for (const [key, rawEntry] of Object.entries(data.images)) {
    const entry = rawEntry as any; // 临时转换，实际结构已由 build script 保证

    images[key] = {
      id: entry.id,
      original: entry.original,
      originalWidth: entry.originalWidth,
      originalHeight: entry.originalHeight,
      originalSize: entry.originalSize,
      variants: entry.variants.map((v: any) => ({
        width: v.width,
        format: v.format as "webp" | "avif",
        filename: v.filename,
        size: v.size,
        url: v.url,
      })),
      srcset: entry.srcset,
      avifSrcset: entry.avifSrcset,
      sizes: entry.sizes,
      blurDataURL: entry.blurDataURL,
      aspectRatio: entry.aspectRatio,
    };
  }

  return {
    version: data.version,
    generated: data.generated,
    images,
  };
}

// 初始化 manifest
const imageManifest = createManifest(rawManifest);

/**
 * Find an image by its original path
 */
export function getImageByPath(originalPath: string): ImageManifestEntry | null {
  const normalized = originalPath.startsWith("/") ? originalPath : `/${originalPath}`;

  return Object.values(imageManifest.images).find((entry) => entry.original === normalized) || null;
}

/**
 * Find an image by its ID (hash)
 */
export function getImageById(id: string): ImageManifestEntry | null {
  return imageManifest.images[id] || null;
}

/**
 * Get the best matching variant for a given width
 */
export function getVariantForWidth(
  entry: ImageManifestEntry,
  targetWidth: number,
  format: "webp" | "avif" = "webp"
): ImageVariant | null {
  // 优先找 >= targetWidth 的最小变体
  const candidates = entry.variants
    .filter((v) => v.format === format && v.width >= targetWidth)
    .sort((a, b) => a.width - b.width);

  if (candidates.length > 0) {
    return candidates[0];
  }

  // 降级：返回该格式下最大的变体
  const all = entry.variants.filter((v) => v.format === format).sort((a, b) => b.width - a.width);

  return all[0] || null;
}

/**
 * Get all variants (optionally filtered by format)
 */
export function getVariants(entry: ImageManifestEntry, format?: "webp" | "avif"): ImageVariant[] {
  if (format) {
    return entry.variants.filter((v) => v.format === format);
  }
  return entry.variants;
}

/**
 * Generate custom srcset
 */
export function generateSrcSet(
  entry: ImageManifestEntry,
  widths: number[],
  format: "webp" | "avif" = "webp"
): string {
  return widths
    .map((w) => getVariantForWidth(entry, w, format))
    .filter((v): v is ImageVariant => v !== null)
    .map((v) => `${v.url} ${v.width}w`)
    .join(", ");
}

/**
 * Get the smallest variant (useful for placeholders)
 */
export function getSmallestVariant(
  entry: ImageManifestEntry,
  format: "webp" | "avif" = "webp"
): ImageVariant | null {
  const variants = entry.variants.filter((v) => v.format === format);
  if (variants.length === 0) return null;

  return variants.reduce((min, v) => (v.width < min.width ? v : min));
}

/**
 * Get all registered images
 */
export function getAllImages(): ImageManifestEntry[] {
  return Object.values(imageManifest.images);
}

/**
 * Get manifest metadata
 */
export function getManifestInfo() {
  return {
    version: imageManifest.version,
    generated: imageManifest.generated,
    imageCount: Object.keys(imageManifest.images).length,
  };
}

/**
 * Check if image exists
 */
export function hasImage(originalPath: string): boolean {
  return getImageByPath(originalPath) !== null;
}
