name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Get Git info and Build Time
        id: git_info
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --pretty=format:%cd --date=iso)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Build static export
        run: npm run build
        env:
          NEXT_PUBLIC_LAST_FM_API_KEY: ${{ secrets.NEXT_PUBLIC_LAST_FM_API_KEY }}
          NEXT_PUBLIC_LAST_FM_USERNAME: ${{ secrets.NEXT_PUBLIC_LAST_FM_USERNAME }}
          NEXT_PUBLIC_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
          NEXT_PUBLIC_BUILD_TIME: ${{ env.BUILD_TIME }}
          NEXT_PUBLIC_COMMIT_DATE: ${{ env.COMMIT_DATE }}
          NEXT_PUBLIC_COMMIT_SHA: ${{ env.COMMIT_SHA }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
